version: '3'

services:
  db:
    image: postgres
    container_name: coss_db
    environment:
      - POSTGRES_USER=coss_user
      - POSTGRES_PASSWORD=coss_password
      - POSTGRES_DB=coss_db
    volumes:
      - postgres_volume:/var/lib/postgresql
  memcached:
    image: memcached
    container_name: coss_memcache
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    links:
      - db
      - memcached
    command: ./bin/run-dev.sh
volumes:
  postgres_volume:
